### ISSUE TITLE
tabTitle 컴포넌트 강제 중앙 배치 문제

### ISSUE THREAD

**Issue by daeun0726** [2024-opensource/Season-ui#3]
## 버그 설명
발생한 문제에 대해 간단히 설명해주세요
- tabTitle 컴포넌트를 사용하면 컴포넌트가 화면의 가로 중앙에 고정 배치되는 문제가 발생합니다. 사용자 설정에 따라 컴포넌트 위치를 변경할 수 없어서 레이아웃 구성에 어려움이 있습니다.

## 버그 재현 방법
보고하고자 하는 버그를 재현하기 위한 단계를 순차적으로 설명해주세요.
1. 해당 라이브러리를 설치하고 프로젝트에 import합니다.
2. Loading 또는 TabList 컴포넌트를 화면의 다른 위치에 배치하려고 시도합니다.
3. 컴포넌트가 화면 가로 중앙에 고정 배치되는 것을 확인합니다.

## 환경
문제가 발생한 환경에 대해 설명해주세요.

OS: Windows 10
Browser Chrome 118.0.0
Version [0.1.5]

## 추가 정보
문제를 해결하는 데 도움이 될 수 있는 다른 추가 정보가 있다면 덧붙여주세요.

**Comment by minji02** [comment]
감사합니다!
